version: '3.1'
services:
  PostgreSQL:
    image: postgres
    networks:
      - mynet
    ports:
      - "5434:5432"
    environment:
      - POSTGRES_PASSWORD=password
      - POSTGRES_USER=postgres
      - POSTGRES_DB=postgres
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U postgres"]
      interval: 10s
      timeout: 5s
      retries: 5

  API:
    container_name: antique-auto-server
    image: abosch1/antique-auto-services
    networks:
      - mynet
    ports:
      - "8080:8080"
    depends_on:
      - PostgreSQL
networks:
  mynet:
    driver: bridge