spring:
  datasource:
    url: jdbc:postgresql://192.168.80.3:5432/postgres
    username: postgres
    password: password
    pool-size: 30
---
server:
  error:
    include-message: always
  port: 8080
