spring:
  datasource:
    url: jdbc:postgresql://PostgreSQL:5434/postgres
    username: postgres
    password: password
    pool-size: 30
---
server:
  error:
    include-message: always
  port: 8080
